import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { Store } from '@/utils/Store';
import { ToastContainer } from 'react-toastify';
import { useContext, useState, useEffect } from 'react';
import { signOut, useSession } from 'next-auth/react';
import { Menu } from '@headlessui/react';
import 'react-toastify/dist/ReactToastify.css'
import DropdownLink from './DropdownLink';
import Cookies from 'js-cookie';

export default function Layout({ title, children }) {

    const { status, data: session} = useSession()
    const { state, dispatch} = useContext(Store);
    const { cart } = state;
    const [cartItemsCount, setcartItemsCount] = useState(0);

    useEffect(() => {
      setcartItemsCount(cart.cartItems.reduce((a,c) => a + c.quantity, 0))
    }, [cart.cartItems]);

    const logoutClickHandler = () => {
      Cookies.remove('cart')
      dispatch({ type: 'CART_RESET'})
      signOut({ callbackUrl: '/login'})
    } 

  return (
    <>
      <Head>
        <title>{title ? title + ' | Amazona' : 'Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="Ecommerce Website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ToastContainer position='bottom-center' limit={1}/>

      <div className='flex min-h-screen flex-col justify-between'>
        <header>
            <nav className='flex h-12 justify-between shadow-md items-center px-4'>
                <Link href={'/'}>
                    <div className='text-lg font-bold'>amazona</div>
                </Link>
                <div className='flex h-12 justify-between items-center px-4'>
                    <Link href={'/cart'}>
                        <p className='p-2'>Cart
                        {cartItemsCount > 0 && 
                        (<span className='ml=1 rounded-full bg-red-600 px-2 py1 text-xs font-bold text-white'>
                            {cartItemsCount}
                        </span>)}
                        </p>
                    </Link>
                    {
                      status === 'loading' ? (
                        'Loading'
                      ) : session?.user? (
                        <Menu as='div' className='relative inline-block'>
                          <Menu.Button className={'text-blue-600'}>
                            {session.user.name}
                          </Menu.Button>
                          <Menu.Items className={'absolute right-0 w-56 origin-top-right bg-white shadow-lg'}>
                            <Menu.Item>
                              <DropdownLink className='dropdown-link' href='/profile'>Profile</DropdownLink>
                            </Menu.Item>
                            <Menu.Item>
                              <a href="#" onClick={logoutClickHandler}>Order History</a>
                            </Menu.Item>
                            <Menu.Item>
                              <DropdownLink className='dropdown-link' href='/order-history'>Logout</DropdownLink>
                            </Menu.Item>
                          </Menu.Items>
                        </Menu>
                      ) : (
                        <Link href={'/login'}>
                        <p className='p-2'>Login</p>
                    </Link>
                      )
                    }
                </div>
            </nav>
        </header>

        <main className='container m-auto mt-4 px-4'>{children}</main>

        <footer className='flex justify-center items-center h-10 shadow-inner'>Copyrigth 2023 Pablo Carro</footer>
      </div>

    </>
  )
}
